### ISSUE TITLE
Duda en los pasos

### ISSUE THREAD

**Issue by nepito** [IslasGECI/reproducibility_inspector#8]
¿@evaristor Serán necesarios los pasos 6 y 9 de [aquí](https://github.com/IslasGECI/reproducibility_inspector)?

**Comment by nepito** [comment]
Cómo hacemos:
- [ ] Monta el disco de datos asuncion en la nueva máquina virtual

Pudimos correr las últimas instrucciones, la de la sección [Construye imagen de docker](https://github.com/IslasGECI/reproducibility_inspector#construye-imagen-de-docker), pero no sabemos cómo estar seguros que lo que hicimos está bien. Creemos que sí  está corriendo pues pusimos `docker ps` y hay un contenedor corriendo desde hace 10 minutos.

**Comment by evaristor** [comment]
@nepito:

El paso 9 sí hay que hacerlo.
El paso 6 hay que platicarlo. Tal vez hay que copiar los volúmenes manualmente con:

```
sudo scp -r ciencia_datos@IP_MAQUINA_ACTUAL_CON_INSPECTOR:/var/lib/docker/volumes /media/NUEVO_DISCO_DURO/docker/
```

**Comment by nepito** [comment]
Aquí está el charrán:
`ssh charran@168.62.4.149`

**Comment by evaristor** [comment]
@nepito @islasfernando : Podrían intentar seguir [el paso 9](https://github.com/IslasGECI/reproducibility_inspector/tree/release/v0.3.0#configuraci%C3%B3n-de-la-m%C3%A1quina-virtual) nuevamente?

**Comment by evaristor** [comment]
Esto se resolverá en #9

**Comment by evaristor** [comment]
Se resolvió en #9
